### ISSUE TITLE
Cannot use 'String' as class name as it is reserved

### ISSUE THREAD

**Issue by set0x** [romanpitak/Nginx-Config-Processor#5]
Not working in php-7

```
Cannot use 'String' as class name as it is reserved
```

**Comment by romanpitak** [comment]
Thanks for the report @set0x. 

https://github.com/romanpitak/Nginx-Config-Processor/commit/428734679ef66dd53ca38c496cb2ef9d581bd653

I'll incorporate it into the next release soon.
