### ISSUE TITLE
How can I create proxy_set_header?

### ISSUE THREAD

**Issue by michalkolar** [romanpitak/Nginx-Config-Processor#9]
I would like create config like this

> location / {
>     proxy_pass       http://localhost:8000;
>     proxy_set_header Host      $host;
>     proxy_set_header X-Real-IP $remote_addr;
> }

but how can I create proxy_set_header X-Real-IP $remote_addr; ?

> Directive::create('proxy_set_header', 'X-Real-IP', '$remote_addr')

does not do the job.

http://nginx.org/en/docs/http/ngx_http_proxy_module.html

**Comment by romanpitak** [comment]
Hi @michalkolar, did you try this?

``` php
Directive::create('proxy_set_header', 'X-Real-IP $remote_addr')
```
